defmodule Experimentwizard.Executer do
  @moduledoc """
  A wrapper around SimpleCluster.Executer module, provides control
  to execute commands on the remote nodes.
  """
  use Agent

  ############# Callbacks #############

  def start_link([nodes, half_name]) do
    # topologies = [
    #   cluster: [
    #     strategy: Cluster.Strategy.Epmd,
    #     config: [hosts: nodes]
    #   ]
    # ]
    # Cluster.Supervisor.start_link([topologies, [name: String.to_atom(half_name <> "ClusterSupervisor")]])
    Agent.start_link(fn -> nodes end, name: String.to_atom(half_name <> "executers"))
  end


  @doc """
  Run asynchronous command on the given node, assume the command is a string.
  """
  def run_async_command(node, command) do
    :erpc.call(node, SimpleCluster.Executer, :run_command, [command, true])
  end

  @doc """
  Run synchronous command on the given node, assume the command is a string.
  """
  def run_sync_command(node, command) do
    :erpc.call(node, SimpleCluster.Executer, :run_command, [command, false])
  end

  @doc """
  Get all running processes started by the Executer on the given remote node.
  """
  def get_all_running_processes(node) do
    :erpc.call(node, SimpleCluster.Executer, :get_all_children, [])
  end

  @doc """
  Kill the process on the given remote node.
  """
  def kill_process(node, ospid) do
    :erpc.call(node, SimpleCluster.Executer, :kill_process, [ospid])
  end

  @doc """
  Send data to the given process on the given remote node.
  """
  def send_data_to_process(node, ospid, data) do
    :erpc.call(node, SimpleCluster.Executer, :send_to_process, [ospid, data])
  end

  @doc """
  Get the result generated by an asynchronous command on the remote node.
  This function will return raw result, which includes the cumulative result
  till this moment as well as if the command is finished or not.
  """
  def get_raw_result(node, ospid) do
    :erpc.call(node, SimpleCluster.Executer, :get_raw_result, [ospid])
  end

  @doc """
  Get the result generated by an asynchronous command on the remote node.
  If the command is still running, this will return partial result.
  """
  def get_partial_result(node, ospid) do
    :erpc.call(node, SimpleCluster.Executer, :get_partial_result, [ospid])
  end

  @doc """
  Get the result generated by an asynchronous command on the remote node.
  If the result is ready, this function will return the result AND DELETE THE RESULT
  saved on the remote node.
  If the result is not yet ready, this function will return nil.
  """
  def get_full_result(node, ospid) do
    :erpc.call(node, SimpleCluster.Executer, :get_full_result, [ospid])
  end

  def change_working_directory(node, working_directory) do
    :erpc.call(node, SimpleCluster.Executer, :change_working_directory, [working_directory])
  end

  def update_env(node, new_env) do
    :erpc.call(node, SimpleCluster.Executer, :extend_env, [new_env])
  end

  ############# Private Helper Functions #############

end
